# Generated by Django 5.2.4 on 2025-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=255)),
                ('course_duration', models.IntegerField()),
                ('course_price', models.IntegerField()),
            ],
        ),
    ]
