# Generated by Django 5.2.4 on 2025-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('re_password', models.CharField(max_length=255)),
                ('is_django', models.BooleanField()),
            ],
        ),
    ]
